import "./globals.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registory";
import Providers from "./components/auth/providers";
import MainHeader from "./components/mainHeader";

// const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <MainHeader />
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
